'use client';
import {FigmaAsset,Icon,icons} from './figma-assets';
import {abstractExcerpt,type Paper,type Evidence} from './paper-data';
import {SourceCitation,type ReferenceActions} from './reference-components';
import type {SearchIntent} from './scholarly/types';
import type {CitationPreferences} from './thread-state';
export function SearchAnswer({selectedEvidence,analysisMessage,onRetryExtraction,onEvidence,query,provider,intent,papers,loading,error,retry,preferences,actions,onReferences,onFilter,onFollowup,showFollowups,onDismiss}:{selectedEvidence?:Evidence;analysisMessage:string;onRetryExtraction:()=>void;onEvidence:(p:Paper,e:Evidence)=>void;query:string;provider:string;intent?:SearchIntent;papers:Paper[];loading:boolean;error:string;retry:()=>void;preferences:CitationPreferences;actions:ReferenceActions;onReferences:()=>void;onFilter:()=>void;onFollowup:(q:string)=>void;showFollowups:boolean;onDismiss:()=>void}) {
  const sources=papers.filter((p,i)=>i<5||Object.values(p.extractions||{}).some(e=>e.status==='supported'));
  return <article className="research-answer"><div className="answer-title-row"><span className="answer-brand"><Icon name={icons.research}/>Paperpal</span><span className="rw-muted">Search papers</span></div>
    <h1>Papers for your research</h1>
    <p className="search-data-note">Live results from {provider}. Abstract excerpts come from source records. {papers.some(p=>p.analysisStatus==='ready')?'Extracted insights link to their supporting passages; cross-paper AI synthesis is not connected yet.':'AI synthesis and enhanced extraction are not connected yet.'}</p>{analysisMessage&&<p className="rw-muted">{analysisMessage} <button className="table-evidence" onClick={onRetryExtraction}>Retry connection</button></p>}{papers.some(p=>p.analysisStatus==='failed')&&<button className="outline-button" onClick={onRetryExtraction}>Retry extraction</button>}
    {intent&&intent.notes.length>0&&<p className="rw-muted" aria-label="Applied query constraints">{intent.notes.join(" ")}</p>}
    {loading&&!papers.length?<div className="answer-loading" role="status" aria-label="Searching papers"><span/><span/><span/></div>:error&&!papers.length?<div className="rw-empty" role="alert"><h3>We couldn’t load your papers</h3><p>{error}</p><button className="outline-button" onClick={retry}>Retry search</button></div>:!papers.length?<div className="rw-empty"><h3>No relevant papers found</h3><p>Try a more specific research topic or a different query.</p></div>:<>
    <p className="answer-intro">{papers.length} references loaded for “{query}”. Explore the source records below and compare them in References.</p>
    {sources.map(p=><section className="answer-section" key={p.id}><h2>{p.title}</h2><p>{p.abstract?<><span className="rw-eyebrow">Abstract excerpt</span><br/>{abstractExcerpt(p)}</>:<>The source provides a bibliographic record{p.journal?` in ${p.journal}`:''}{p.year?` (${p.year})`:''}. An abstract is not available for this paper.</>} <SourceCitation paper={p} number={papers.indexOf(p)+1} label={preferences.citationFormat==='numeric'?`[${papers.indexOf(p)+1}]`:[p.shortAuthor,p.year].filter(Boolean).join(', ')||`Source ${papers.indexOf(p)+1}`} actions={actions}/></p>{p.analysisStatus==='loading'&&<p role="status">Analysing source text…</p>}{Object.entries(p.extractions||{}).filter(([,cell])=>cell.status==='supported').map(([id,cell])=><section id={cell.claimId} key={id} className={`answer-section ${selectedEvidence?.claimId===cell.claimId?'linked-claim':''}`}><h3>{id==='summary'?'Question-specific summary':id==='relevance'?'Relevance':id==='pathway'?'Pathway':'Extracted insight'}</h3><p>{cell.value}</p>{p.evidence.filter(e=>cell.evidenceIds?.includes(e.id)).map(e=><button className="table-evidence" key={e.id} onClick={()=>onEvidence(p,e)}>View evidence · {e.sourceType==='abstract'?'Abstract':`Page ${e.page}`}</button>)}</section>)}</section>)}
    <div className="answer-actions"><button className="rw-action" onClick={onReferences}>References ({papers.length})</button><button className="rw-action" onClick={onFilter}><Icon name="filter-sliders"/>Filters</button></div>
    {showFollowups&&<section className="followup-suggestions" aria-labelledby="followup-heading"><div className="followup-heading"><h2 id="followup-heading">What would you like to do next?</h2><button className="followup-dismiss" aria-label="Dismiss follow-up suggestions" onClick={onDismiss}><FigmaAsset name="followup-xmark"/></button></div><div className="followup-options">{['Compare the available abstracts','Explore the methods in these papers','What limitations are reported?'].map(q=><button className="followup-option" key={q} onClick={()=>onFollowup(q)}><span className="followup-icon-tile"><span className="followup-sparkle" style={{maskImage:`url(${process.env.NEXT_PUBLIC_BASE_PATH||''}/figma/followup-sparkles.svg)`}}/></span><span className="followup-label">{q}</span><FigmaAsset name="followup-chevron-left" className="followup-chevron"/></button>)}</div></section>}
    </>}
  </article>;
}
