"""Record exact installed dependency versions for reproducible Python installations."""
from importlib import metadata
from pathlib import Path
import tomllib

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

root = Path(__file__).resolve().parents[1] / "services/research"
project = tomllib.loads((root / "pyproject.toml").read_text())["project"]


def resolve(requirements: list[str]) -> list[str]:
    pending = [Requirement(value) for value in requirements]
    visited: set[tuple[str, tuple[str, ...]]] = set()
    versions: dict[str, str] = {}
    while pending:
        req = pending.pop()
        key = (canonicalize_name(req.name), tuple(sorted(req.extras)))
        if key in visited:
            continue
        visited.add(key)
        package = metadata.distribution(req.name)
        versions[key[0]] = package.version
        for value in package.requires or []:
            child = Requirement(value)
            if child.marker is None or any(
                child.marker.evaluate({"extra": extra}) for extra in {"", *req.extras}
            ):
                pending.append(child)
    return [f"{name}=={version}" for name, version in sorted(versions.items())]


for filename, requirements in (
    ("requirements.lock", project["dependencies"]),
    ("requirements-dev.lock", project["dependencies"] + project["optional-dependencies"]["dev"]),
):
    (root / filename).write_text(
        "# Generated by scripts/lock_python.py for Python 3.12 on macOS/Linux.\n"
        + "\n".join(resolve(requirements)) + "\n"
    )
print("Updated production and development Python dependency locks.")
